module.exports = {

  darkMode: 'class',
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      'white': '#ffffff',
      'navy_night_anemone': '#1C0248',
      'pink_clownfish': '#FFA4CA',
      'blue_fishtank': '#30B7D5',
      'red_goldfish': '#FF2D1D',
      'yellow_turtle': '#FCD901',
      /* cara theme color setup */
      'primary': '#FCD901',
      'secondary': '#1C0248',
      'text': '#1C0248',
      'nav_links': '#ffffff',
      'button_yellow': '#FF2D1D',
      'button_yellow_hover': '#1C0248',
      'button_pink': '#FF2D1D',
      'button_pink_bg': '#FFA4CA',
      'button_pink_hover': '#1C0248',
      'button_blue': '#FCD901',
      'button_blue_hover': '#1C0248',
      'button_toggle': '#1C0248',
      'button_toggle_bg': '#FFA4CA',
      'button_toggle_hover': '#FF2D1D',
      'hero_heading': '#FFA4CA',
      'heading': '#1C0248',
      'background': '#1C0248',
      'divider': '#1C0248',
      'color_divider_bg': '#1C0248',
      'color_divider_heading': '#FCD901',
      'color_divider_text': '#ffffff',
      'wave': '#ffffff',
      'mobile_menu': '#1C0248',
      'textMuted': '#FF2D1D',
      'icon_brightest': 'rgba(255, 255, 255, 0.04)',
      'icon_darker':  'rgba(255, 255, 255, 0.08)',
      'icon_darkest':  'rgba(255, 255, 255, 0.16)',
      'icon_red': '#FF2D1D',
      'icon_blue': '#30B7D5',
      'icon_orange': '#FF2D1D',
      'icon_yellow': '#FCD901',
      'icon_pink': '#FFA4CA',
      'icon_purple': '#30B7D5',
      'icon_green': '#FCD901',
      modes: {
        light: {
          text: '#1C0248',
          nav_links: '#1C0248',
          secondary: '#1C0248',
          button_yellow: '#1C0248',
          button_yellow_hover: '#FF2D1D',
          button_pink: '#1C0248',
          button_pink_bg: '#FFA4CA',
          button_pink_hover: '#FF2D1D',
          button_blue: '#1C0248',
          button_blue_hover: '#FCD901',
          button_toggle: '#FFA4CA',
          button_toggle_bg: '#1C0248',
          button_toggle_hover: '#FCD901',
          hero_heading: '#1C0248',
          heading: '#1C0248',
          primary: '#FF2D1D',
          background: '#FFA4CA',
          divider: '#ffffff',
          color_divider_bg: '#FCD901',
          color_divider_heading: '#1C0248',
          color_divider_text: '#1C0248',
          wave: '#ffffff',
          mobile_menu: '#ffffff',
          textMuted: '#FCD901',
          icon_pink: '#1C0248',
          icon_yellow: '#FCD901',
          icon_brightest: 'rgba(28, 2, 72, 0.04)',
          icon_darker:  'rgba(28, 2, 72, 0.08)',
          icon_darkest:  'rgba(28, 2, 72, 0.16)',
        },
      },
    },
    extend: {
    },
  },
  plugins: [],
}
